### ISSUE TITLE
take a first stab at mappings across different environmental packages

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs-rdf#1]
@wdduncan take a first stab at mappings across different environmental packages

Copy of GenomicsStandardsConsortium/mixs-ng#2

**Comment by wdduncan** [comment]
@ramonawalls  
I've added a notebooks directory with an analysis of the terms. The description is in the notebooks/README file. Please let me know if something doesn't make sense. BTW, you don't need to run the notebook. You can simply view the outputs.

**Comment by cmungall** [comment]
https://github.com/GenomicsStandardsConsortium/mixs-rdf/blob/master/notebooks/common-mixs-package-terms.ipynb

**Comment by ramonawalls** [comment]
Look for MIXS issue that closes this package.

**Comment by ramonawalls** [comment]
Will probably treat packages as classes.
