### ISSUE TITLE
MIXS ID is overloaded

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs-rdf#23]
In the mixs spreadsheets, there is a MIXS ID column on both the MIxS and environmental_package tabs. But the use of the column seems to be overloaded.  

For example on the mixs_v5 `environmental_package` tab,  I think (based on info from the last call) that the mix id is used to identify the occurrence of a term within a package. For example, `depth` has multiple mix ids depending on package: `MIXS:0000240, MIXS:0000485, MIXS:0000520, MIXS:0000549, MIXS:0000592, MIXS:0000632, MIXS:0000654, MIXS:0000674`   

But, on the mixs_v5 `MIxS` tab, `depth` has a single mixs id of `MIXS:0000018`. I assume (perhaps wrongly) that on MIxS ID on the MIxS tab is intended to uniquely identify the term.

cc @cmungall @ramonawalls

**Comment by ramonawalls** [comment]
This has been resolved. https://docs.google.com/spreadsheets/d/1p5Ziciznkk9er99aPhc7ed8NDE0oUKw0rrBlEOYUtiA/edit#gid=0
