### ISSUE TITLE
Requirement values: conditional mandatory and environment-dependent requirements

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs-rdf#24]
The 'Requirement' column on can have a value 'C' -> "conditional mandatory". Not sure what this means. Does it mean?:
- The mandatory status is based on the package. This makes the most sense to me, but the combination of package + term would cover this, and on the evironment package tab there are 'C's in the requirement field.
- The mandatory status is based on the value another term in the enironmental package? If so, whic term?

Also, the environment-dependent requirement value (E). Further confuses me. How is this different than a term being conditionally required?   

Can someone help my understand?

cc @cmungall @ramonawalls @folker @jdeck88

**Comment by pyilmaz** [comment]
Hi Bill! I think I can give a historical summary of why C and E exist. 
C means value of field should be given, if it applied to experiment/sample in question. It does not mean that mandatory status is based on package. Let's take specific host for example, for bacterial genomes, this would make sense and would be great to know if the bacteria is host associated (like plant symbionts), but in other cases would not make sense. So it is a soft mandatory field...
E means conditionally mandatory based on the environmental package - over time, we saw that making altitude/depth for human environment did not make sense, but we still wanted to keep these fields prominent in the MIxS checklist

**Comment by ramonawalls** [comment]
This is working for now.
