### ISSUE TITLE
MIxS checklist terms vs environmental package terms

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs-rdf#25]
In MIxS v5, there are only 3 terms in the MIxS tab (i.e., the MIxS check list), that are also on the environmental_packages tab:
```
alt
depth
elev
```
Shouldn't there by more? 

cc @cmungall @ramonawalls @folker @jdeck88

**Comment by ramonawalls** [comment]
Close this and merge it with #4 .
