### ISSUE TITLE
MIxS checklist available in other formats

### ISSUE THREAD

**Issue by mia-lgo** [GenomicsStandardsConsortium/mixs-rdf#33]
Dear all,

To begin with: Happy 2021!!

Now to the point: 
The colleagues at the University of Tübingen are currently in the process of developing a system for and with plant biologists. They are wondering if the MIxS schema could be available in other formats (besides xlsx), preferably XSD (alternatively XML or any other type).
Is a conversion to xsd feasible?

**Comment by ramonawalls** [comment]
With MIxS 7 it will be available in JSON, which should be easy to convert to XSD. We should discuss providing other formats with the release.

**Comment by johanneswerner** [comment]
Thank you for the information. When will MIxS 7 be available (and is there any way to use JSON or XSD format before that release)?

**Comment by only1chunts** [comment]
MIxS v6 is due for release within the next couple of months. We will then start on MIxSv7 with the aim of completing early 2022. However, as you are obviously keen to make use of it we would be MORE than happy to have you work with us on it, we are all volunteers and would greatly appreciate any assistance you can provide, and if it could mean pushing the RDF/JSON version planned for v7 out before the end of 2021 that would be amazing!

**Comment by johanneswerner** [comment]
I would be happy to contribute. What would be a good way to get in contact?

**Comment by only1chunts** [comment]
Thats great news, thank you.
We have group calls that you can join in with:
RDF working group on 2nd Monday of every month
CIG* on 4th Monday of every month
*CIG= Compliance and Interoperability Group
These two groups are largely overlapping in people attending! 
The focus at the moment of the CIG call is getting the terms and new checklists vetted to be able to release v6.
The RDF group calls are aiming to get the technology ready and working to port all the v6 terms and checklists into as soon as they are vetted.
Details of all calls are posted to the group email, you can join the group [here ](https://groups.google.com/g/genomic-standards-consortium) or send an email to gensc-cig@googlegroups.com 
The next scheduled call is 25th Jan for CIG, but @ramonawalls or @cmungall may know of RDF related tasks that could be worked on prior to that if want to get started.

**Comment by mia-lgo** [comment]
Thank you both Chris and Ramona fur such a quick and complete response :) I'll see you at the next CIG meeting.

**Comment by ramonawalls** [comment]
I meant MIxS 6 in my comment! So happy to have your input @mia-lgo.
